# Generated by Django 5.0.4 on 2024-09-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Image', 'Image')], max_length=10)),
                ('format', models.CharField(max_length=10)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_secs', models.IntegerField(default=0)),
            ],
        ),
    ]
